# Generated by Django 4.2.4 on 2023-08-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=10)),
                ('price_bought', models.BigIntegerField(default=0)),
                ('buffer', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=10)),
                ('price_bought', models.BigIntegerField(default=0)),
                ('fraction_bought', models.FloatField(default=0.0)),
            ],
        ),
    ]
